### PR TITLE
Remove unreachable code and add generate commands to test types

### PR DESCRIPTION
**Pull request by BenjaminTrapani**
Golint uncovered some unreachable code in the generated output which was likely present before recent modifications but had been corrected via gofmt -w -s . This PR removes the unreachable code.

### CODE REVIEW

**Review by bfallik — COMMENTED** [review]
Is the unreachable code lines we added or from upstream? If it's upstream it may make sense to keep them despite the lint warnings to reduce our divergence.

**Comment by BenjaminTrapani** [comment]
@bfallik The unreachable code is a result of the Scan function we added.

**Review by bfallik — APPROVED** [review]
OK

**Comment by andrei-m** [comment]
@BenjaminTrapani OK to merge?

**Pull request merged**
