### PR TITLE
convert ATRU source to iota type

### PR DESCRIPTION
**Pull request by BenjaminTrapani**
https://clypdinc.atlassian.net/browse/MAIN-19181

### CODE REVIEW

**Comment by BenjaminTrapani** [comment]
@jamesgarfield Per your suggestion on the closed PR

**Comment by jamesgarfield** [comment]
👍

**Comment by BenjaminTrapani** [comment]
@quintenpalmer Does this change make sense to you?

**Review by quintenpalmer — APPROVED** [review]
LGTM

**Pull request merged**
